name: castflow
description: "Castflow - Casting management platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.8.0
  firebase_auth: ^6.5.0
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.3
  cloud_firestore: ^6.4.0
  firebase_storage: ^13.4.0
  image_picker: ^1.2.2
  shared_preferences: ^2.5.5
  csc_picker_plus: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
